# Generated by Django 3.1.6 on 2021-04-03 22:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Belongings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('address', models.TextField()),
                ('image', models.ImageField(default='default.jpg', upload_to='')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('settled', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('belonging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='estate.belongings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
        migrations.AddField(
            model_name='belongings',
            name='estate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.estate'),
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('statusID', models.AutoField(primary_key=True, serialize=False)),
                ('alternatives', models.CharField(choices=[('N/A', 'N/A'), ('Fordele', 'Fordele'), ('Donere', 'Donere'), ('Kaste', 'Kaste')], max_length=30)),
                ('rating', models.IntegerField(blank=True, default=0, null=True)),
                ('belonging', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='estate.belongings')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('belonging', 'user')},
            },
        ),
    ]
